/**
 * Generates supabase/seeds/bitclout_reserved_usernames.sql from DeSo's
 * canonical reserved_usernames.go file.
 *
 * Run once when the upstream list changes:
 *   npx tsx scripts/generate-reserved-usernames-seed.ts
 *
 * Source: deso-protocol/core@main/lib/reserved_usernames.go
 * Format: a Go map literal `var IsReserved = map[string]bool{ "name": true, ... }`.
 *
 * The output is committed to git so production builds don't need network access.
 */
import { writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";

const SOURCE_URL =
  "https://raw.githubusercontent.com/deso-protocol/core/main/lib/reserved_usernames.go";
const OUT_PATH = resolve(
  process.cwd(),
  "supabase/seeds/bitclout_reserved_usernames.sql"
);

const ENTRY_RE = /^\s*"([^"]+)":\s*(true|false),?\s*$/gm;
const BATCH_SIZE = 500;

async function main(): Promise<void> {
  console.log(`[reserved-seed] Fetching ${SOURCE_URL}`);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    throw new Error(`Failed to fetch source: ${res.status} ${res.statusText}`);
  }
  const source = await res.text();

  const entries = new Map<string, boolean>(); // dedupe by lowercased username
  let match: RegExpExecArray | null;
  while ((match = ENTRY_RE.exec(source)) !== null) {
    const username = match[1].toLowerCase();
    const hasBlueCheck = match[2] === "true";
    // If the same username appears twice, prefer the more permissive (true)
    // value so we never lose a blue-check signal.
    const existing = entries.get(username);
    if (existing === undefined || (hasBlueCheck && !existing)) {
      entries.set(username, hasBlueCheck);
    }
  }

  if (entries.size === 0) {
    throw new Error("Parsed 0 entries — check the regex against the source");
  }

  const sorted = [...entries.entries()].sort(([a], [b]) => a.localeCompare(b));
  const lines: string[] = [];
  lines.push("-- Generated by scripts/generate-reserved-usernames-seed.ts");
  lines.push(`-- Source: ${SOURCE_URL}`);
  lines.push(`-- Entries: ${sorted.length}`);
  lines.push("-- Regenerate by running: npx tsx scripts/generate-reserved-usernames-seed.ts");
  lines.push("");
  lines.push("DROP TABLE IF EXISTS bitclout_reserved_usernames;");
  lines.push("");
  lines.push("CREATE TABLE bitclout_reserved_usernames (");
  lines.push("  username TEXT PRIMARY KEY,");
  lines.push("  has_blue_check BOOLEAN NOT NULL DEFAULT false");
  lines.push(");");
  lines.push("");

  // Helper: SQL-escape a username (single-quote → double single-quote).
  const esc = (s: string): string => s.replace(/'/g, "''");

  for (let i = 0; i < sorted.length; i += BATCH_SIZE) {
    const batch = sorted.slice(i, i + BATCH_SIZE);
    const values = batch
      .map(([u, b]) => `  ('${esc(u)}', ${b ? "TRUE" : "FALSE"})`)
      .join(",\n");
    lines.push(
      "INSERT INTO bitclout_reserved_usernames (username, has_blue_check) VALUES"
    );
    lines.push(values + ";");
    lines.push("");
  }

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, lines.join("\n"), "utf8");

  console.log(
    `[reserved-seed] Generated seed for ${sorted.length} reserved usernames`
  );
  console.log(`[reserved-seed] Written to ${OUT_PATH}`);
}

main().catch((err) => {
  console.error("[reserved-seed] failed:", err);
  process.exit(1);
});
